### ISSUE TITLE
Evaluate 4337 Module Changes For EntryPoint 0.7.0

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#215]
Evaluate the required Safe 4337 Module contract changes required for the `EntryPoint` version 0.7. This should use the “candidate” `EntryPoint` version that was submitted for audit.

The expected outcome of this issue is:
1. A detailed task summary of required code changes
2. List of additional supporting tasks required for the new module version related to a new release
3. _Optional:_ Draft PR containing code and test changes

**Comment by mmv08** [comment]
There are no migration docs except the [release notes](https://docs.google.com/document/d/156ysKjY1ZzeNsgzvhMKSzN9MlkWnWa4DWKkISdfNYqQ/edit), and the quality feels subpar, to be honest. It feels strange to be pushed to update, given that the documentation is insufficient. But anyway, I went through the release notes' changes one by one.

1. [Simulation functions removed from deployed EntryPoint](https://github.com/eth-infinitism/account-abstraction/pull/321). - Irrelevant for accounts
2. [Added `delegateAndRevert()` helper in EntryPoint to accommodate nodes without state overrides in eth_call and eth_estimateGas](https://github.com/eth-infinitism/account-abstraction/pull/365) - Irrelevant for accounts
3. [Added ERC-165 "supportsInterface" to the EntryPoint.](https://github.com/eth-infinitism/account-abstraction/pull/331) - We could add an erc-165 check during module deployment, but I don't think it's necessary and the contract should be tested anyway.
4. [Added a sample TokenPaymaster.](https://github.com/eth-infinitism/account-abstraction/pull/286) - This should be relevant if we decide to go for a paymaster contract.
5. [Added a 10% penalty charge for unused execution gas limit.](https://github.com/eth-infinitism/account-abstraction/pull/356) - Should be relevant for our SDKs. It's interesting that they charge the penalty on all unused gas; I'd expect a certain threshold after which the penalty applies because gas calculations can sometimes be complicated.
6. [Removed paymaster’s second call to postOp.](https://github.com/eth-infinitism/account-abstraction/pull/311) - Irrelevant for us atm
7. [Added validatePaymasterUserOp and postOp gas limits.](https://github.com/eth-infinitism/account-abstraction/pull/363) - Basically, paymaster and account gas limits are separate now. So far the biggest change for us.
![image](https://github.com/safe-global/safe-modules/assets/16622558/6024767f-12b6-43be-8075-a26c66ed95ba)
8. [Added “gasPrice” parameter to paymaster’s postOp](https://github.com/eth-infinitism/account-abstraction/pull/395) - Irrelevant for us atm
9. [Separated offchain UserOperation and packed UserOperation onchain struct](https://github.com/eth-infinitism/account-abstraction/pull/363). - Not sure I fully understand this change, this seems to be related to 7)
10. [Added a new optional account contract api method `executeUserOp()`](https://github.com/eth-infinitism/account-abstraction/pull/380). - This matches our method name but with different parameters (this one gets the hash and full user operation struct). I don't see much value in adding it because we do not access any of the struct values.

So, that makes the action items:
- **Mandatory** - use the new `PackedUserOperation` struct with packed gas fields
- **Question** - add an erc-165 interface check during module deployment for the entrypoint address?
- **Question** - support the new `executeUserOp` method. We could include it for better developer tooling compatibility.

**Comment by nlordell** [comment]
> add an erc-165 interface check during module deployment for the entrypoint address?

Is this required by the IAccount interface?

**Comment by mmv08** [comment]
> Is this required by the IAccount interface?

No, it's not about the account, it's about the entrypoint contract.

> What does this entail? Just changing the signature of the existing executeUserOp function?

I would not change it but add a new method, I have a gut feeling the new method would use more gas due to more complicated calldata encoding.
