### ISSUE TITLE
Initial Design for Safe Delay-Based Recovery Module

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#348]

**Comment by mmv08** [comment]
Do you think existing options like Zodiac should be considered? I think the Wallet team uses the delay module for the recovery

**Comment by Sednaoui** [comment]
If you would like to consider the safe recovery module that candide has built. The module supports: 

- A Recovery Delay Period
- An Owner can add or remove guardians at anytime
- Guardians can remian private with fresh addresses
- Each recovery contact can submit their signature transactions separately. Once the threshold is meant, anyone can call execute recovery to start the grace period.
- Anyone can execute the guardians aggregated signatures. The last guardian can execute the transaction directly and pay gas fees. This is similar to how Safe's interface works when multiple owners for a multisig sign transactions before submitting them.

Here is the relevant links: 

- [walkthrough](https://docs.candide.dev/blog/making-accounts-recoverable/)
- [smart contracts](https://github.com/candidelabs/CandideWalletContracts/blob/main/contracts/modules/social_recovery/SocialRecoveryModule.sol)

As part of SGP, we're integrating this module into _abstractionkit_. We've also built a version for Safe{core} protocol that we have yet to publish.

**Comment by nlordell** [comment]
@remedcu - can you clarify what our conclusion here was so it is documented in GitHub?

**Comment by remedcu** [comment]
The Safe Team have created an MVP for designing the Safe Recovery Module for this task on the Internal Notion Page. But based on the comments above, we are also exploring other viable options like Candide Recovery Module, Delay Based Module, etc. A final decision will be shared in #352 once things are finalized based on the requirements and the currently available solutions.

As this issue was intended to create a general design and additionally check the current ecosystem products, this issue is considered complete.
