### ISSUE TITLE
Release Safe v1.3.0 With Updated JS Tooling

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-modules#467]

**Comment by mmv08** [comment]
So, this turns out to be a much bigger effort than I anticipated. While a version with the updated JS tooling exists and can be used for deploying contracts, all the periphery code that uses the JS tooling obviously doesn’t work (execution helpers, tests, etc) and requires an update. Since our primary goal was to make a version that can be used to deploy contracts using more modern tooling, we decided to leave the code in a branch:
https://github.com/safe-global/safe-smart-account/tree/v1.3.0-1

Instructions on using:
1. Install dependencies
```
npm i --ignore-scripts
```
`--ignore-scritps` is needed to skip the failing build step
2. Follow the documentation for deployment steps.
